version: 2
sphinx:
  configuration: docs/conf.py
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - openjdk-11-jdk
python:
  install:
     - requirements: docs/requirements.txt
